name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: out
          path: out
      - uses: actions/setup-clojure@13
        with:
          cli: latest
      - uses: actions/cache@v4
        with:
          key: cljdeps-${{ hashFiles('deps.edn') }}
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.deps.clj
      - name: Test
        run: clj -M:test
      - name: Set up build environmental variable
        run: echo "ROOT_FOLDER=/stats/" >> "$GITHUB_ENV"
      - name: Build
        run: clj -M:build out
      - name: Copy public files
        run: cp -r public/* out/
      - uses: actions/upload-pages-artifact@v3
        with:
          path: out/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
