name: Quality Assurance

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: shadow-cljs
          path: .shadow-cljs
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
